spring.application.name=Reimbursement_Portal
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/reimbursement_db
spring.datasource.username=
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080

# Logging
logging.level.org.springframework=INFO