spring.application.name=todo_application
# In-memory H2 database configuration (non-persistent, for development/testing)
spring.datasource.url=jdbc:h2:mem:testdb

# Automatically updates database schema based on JPA entities
spring.jpa.hibernate.ddl-auto=update

# Enables H2 web console for database inspection
spring.h2.console.enabled=true


logging.level.root=INFO

logging.level.com.example.todo_application=DEBUG

logging.pattern.console=%d{HH:mm:ss} - %msg%n